import os
from dotenv import load_dotenv
load_dotenv()

INSTA_USERNAME = os.getenv('INSTA_USERNAME')
INSTA_PASSWORD = os.getenv('INSTA_PASSWORD')
INSTA_DEFAULT_COMMENT = os.getenv('INSTA_DEFAULT_COMMENT')
INSTA_POST_LIKE_COUNT = 5
INSTA_POST_COMMENT_COUNT = 5
INSTA_POST_COMMENT_AND_LIKE_COUNT = 2
INSTA_MESSAGE_TO_SEND = os.getenv('INSTA_MESSAGE_TO_SEND')
INSTA_HASHTAGS = os.getenv('INSTA_HASHTAGS').split(',')
INSTA_USERNAMES = os.getenv('INSTA_USERNAMES').split(',')
